server:
  servlet:
    context-path: /

spring:
  application:
    name: seata-order

  profiles:
    active:
      - dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html;charset=UTF-8

